id: IF4581F14
legacy_id: P007001
ocr_import_info:
  bdrc_scan_id: W2CZ8065
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T14:23:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:57:10.489991+00:00'
last_modified: 2022-09-02 23:57:33.995480
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8065
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8065
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་འབྲུ་འགྲེལ་རྣམ་མཁྱེན་ཐར་གླིང་བགྲོད་པའི་ཐེམ་སྐས།
  author: སྔགས་འཆང་མགོན་པོ་ཚེ་བརྟན།
statistics:
  ocr_word_mean_confidence_index: 0.6132678576525958
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1PD96640:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96640
      total_pages: 212
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96640.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6132678576525958
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
