id: P007001
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:20.866802
source_metadata:
  id: bdr:W2CZ8065
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་འབྲུ་འགྲེལ་རྣམ་མཁྱེན་ཐར་གླིང་བགྲོད་པའི་ཐེམ་སྐས་
  author: ''
  volumes:
    825a62185b22486eae7b51993d1c8b96:
      image_group_id: I1PD96640
      title: Volume 1 of snying thig sngon 'gro'i 'bru 'grel rnam mkhyen thar gling
        bgrod pa'i them skas
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
