id: P007001
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8065
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་འབྲུ་འགྲེལ་རྣམ་མཁྱེན་ཐར་གླིང་བགྲོད་པའི་ཐེམ་སྐས་
  author: ''
  volumes:
    f0c9e589f9aa48c88dccfbefb33ad9f3:
      image_group_id: I1PD96640
      title: ''
      volume_number: 1
      total_pages: 212
ebook_metadata:
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་འབྲུ་འགྲེལ་རྣམ་མཁྱེན་ཐར་གླིང་བགྲོད་པའི་ཐེམ་སྐས་
  author: ''
  sku: P007001
  cover: cover.jpg
  layers:
  - pagination
